spring.application.name=billing-service


server.port=4001
grpc.server.port=9001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

billing.service.address=billing-service
billing.service.grpc.port=9090


