syntax = "proto3";

option java_multiple_files = true;
option java_package = "doctor";
option java_outer_classname = "DoctorProto";

service DoctorServices {

  rpc GetDoctorsBySpecialization(DoctorSpecializationRequest)
      returns (DoctorListResponse);

}

enum Specialization {
  GENERAL_PHYSICIAN = 0;
  CARDIOLOGIST = 1;
  NEUROLOGIST = 2;
  ORTHOPEDIC = 3;
  DERMATOLOGIST = 4;
  PEDIATRICIAN = 5;
  GYNECOLOGIST = 6;
  OPHTHALMOLOGIST = 7;
  ENT_SPECIALIST = 8;
  PSYCHIATRIST = 9;
  UROLOGIST = 10;
  ONCOLOGIST = 11;
  ENDOCRINOLOGIST = 12;
  PULMONOLOGIST = 13;
  GASTROENTEROLOGIST = 14;
  NEPHROLOGIST = 15;
}

message DoctorSpecializationRequest {
  Specialization specialization = 1;
}

message DoctorResponse {

  string id = 1;
  string first_name = 2;
  string last_name = 3;
  string email = 4;
  string specialization = 5;
  string phone_number = 6;
  string qualification = 7;
  int32 experience = 8;
}

message DoctorListResponse {
  repeated DoctorResponse doctors = 1;
}