syntax = "proto3";

package prescription.events;

option java_multiple_files = true;
option java_package = "prescription.events";
option java_outer_classname = "PrescriptionEventProto";

enum PrescriptionEventType {
  PRESCRIPTION_CREATED = 0;
  PRESCRIPTION_DELETED = 1;
}

message PrescriptionEvent {

  string prescriptionId = 1;

  string patientId = 2;

  string doctorId = 3;

  string diagnosis = 4;

  repeated string medicines = 5;

  double consultationFee = 6;

  string prescribedAt = 7;

  string notes = 8;

  string billId = 9;

  PrescriptionEventType eventType = 10;

  int64 occurredAt = 11;
}