package com.pm.patientservice.enums;

public enum Specialization {
    GENERAL_PHYSICIAN,
    CARDIOLOGIST,
    NEUROLOGIST,
    ORTHOPEDIC,
    DERMATOLOGIST,
    PEDIATRICIAN,
    GYNECOLOGIST,
    OPHTHALMOLOGIST,
    ENT_SPECIALIST,
    PSYCHIATRIST,
    UROLOGIST,
    ONCOLOGIST,
    ENDOCRINOLOGIST,
    PULMONOLOGIST,
    GASTROENTEROLOGIST,
    NEPHROLOGIST
}